language: ruby

matrix:
    include:
        - os: osx
          osx_image: xcode8
          env: PYTHON_VERSION=python3
        - os: osx
          osx_image: xcode8
          env: PYTHON_VERSION=python
        - os: osx
          osx_image: xcode7.3
          env: PYTHON_VERSION=python3
        - os: osx
          osx_image: xcode7.3
          env: PYTHON_VERSION=python

install:
    - brew update

script:
    # - brew audit --strict ./Formula/*.rb
    - if [ "$PYTHON_VERSION" == "python3" ]; then
        brew install --verbose --build-bottle ./Formula/*.rb --with-python3;
      else
        brew install --verbose --build-bottle ./Formula/*.rb;
      fi
