language: ruby
matrix:
    include:
        - os: osx
          osx_image: xcode8
        - os: osx
          osx_image: xcode7.3
install:
    - brew update
script:
    - brew audit --strict ./Formula/*.rb
    - brew install --verbose --build-bottle ./Formula/*.rb
